name: pycube
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - numpy>=1.21
  - scipy>=1.7
  - astropy>=4.3
  - setuptools>=46.4
  - matplotlib>=3.4
  - ipython>=7.27
  - ginga>=3.2
  - qtpy>=1.11
  - pyqt<6.0
  - pytest>=6.2
  - bottleneck
  - scikit-image
